# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: platform
      type: github
      name: RMS/cloud-platform
      endpoint: RMS

trigger: none

stages:
- stage: Build
  jobs: 
  - template: sdp/lib/build.yaml@platform
    parameters:
      targets:
      - target: 
        name: rest-api
        lang: java
        tests: true        
      - target: 
        name: rest-service
        lang: java
      - target: 
        name: rest-service
        lang: docker
- stage: Deploy
  dependsOn: Build
  jobs: 
  - template: sdp/lib/deploy.yaml@platform
    parameters:
      services: 
      - service:
        name: sdp-onboard-svc1
        

