resources:
  repositories:
    - repository: platform
      type: github
      name: RMS/cloud-platform
      endpoint: RMS

trigger: none

variables:
- group: cicd-agent-properties

stages: 
- template: sdp/pipeline.yaml@platform
  parameters:
    version: 1.0
    targets:
    - target: 
      name: rest-api
      lang: java
      tests: true        
    - target: 
      name: rest-service
      lang: java
    - target: 
      name: rest-service
      lang: docker
    services: 
    - service:
      name: sdp-onboard-svc1
