---
serviceName: sdp-onboard-svc1
microservices:
    - name: rest-service
      image: rest-service
      httpPath: /(.*)
      rewriteTarget: /$1
      containerPort: 8000
      internalServicePort: 80
      replicas: 1
