name: rest-api
targets:
- !java
  type: java
  #dependencies:
  #- type: maven
  #  repository: remote
  tests:
  - type: maven
    debug: true
  outputs:
  - type: maven
    repository: local
    artifacts:
    - com.rms.samples:rest-api
    