name: rest-api
targets:
- !java
  type: java
  name: rest-api
  tests:
  - type: maven
    debug: true
  outputs:
  - type: maven
    repository: local
    artifacts:
    - rest-api
    - rest-common
    - rest-core
