name: rest-service
targets:
- !java
  type: java
  name: rest-service
  dependencies:
  - type: maven
    repository: local
    artifacts: 
    - rest-api:1.1
  tests:
  - type: unittest
    debug: true
  outputs:
  - type: maven
    repository: local
    artifacts:
    - rest-service
- !docker
  type: docker
  imageName: rest-service
  dockerFile: Dockerfile
  buildArgs:
    - artifact:rest-service-$(Target.Version).jar
