name: rest-service
targets:
- !java
  type: java
  name: rest-service
  dependencies:
  - type: maven
    repository: local
    artifacts: 
    - rest-api
  tests:
  - type: maven
    debug: true
  outputs:
  - type: maven
    repository: local
    artifacts:
    - rest-service
- !docker
  type: docker
  name: rest-service